// flow-typed signature: ed1966471f56b25190adabc9c4148899
// flow-typed version: <<STUB>>/geodesy_v^1.1.3/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geodesy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geodesy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geodesy/dms' {
  declare module.exports: any;
}

declare module 'geodesy/latlon-ellipsoidal' {
  declare module.exports: any;
}

declare module 'geodesy/latlon-spherical' {
  declare module.exports: any;
}

declare module 'geodesy/latlon-vectors' {
  declare module.exports: any;
}

declare module 'geodesy/latlon-vincenty' {
  declare module.exports: any;
}

declare module 'geodesy/mgrs' {
  declare module.exports: any;
}

declare module 'geodesy/npm' {
  declare module.exports: any;
}

declare module 'geodesy/osgridref' {
  declare module.exports: any;
}

declare module 'geodesy/test/dms-tests' {
  declare module.exports: any;
}

declare module 'geodesy/test/latlon-spherical-tests' {
  declare module.exports: any;
}

declare module 'geodesy/test/latlon-vectors-tests' {
  declare module.exports: any;
}

declare module 'geodesy/test/latlon-vincenty-tests' {
  declare module.exports: any;
}

declare module 'geodesy/test/os-gridref-tests' {
  declare module.exports: any;
}

declare module 'geodesy/test/utm-mgrs-tests' {
  declare module.exports: any;
}

declare module 'geodesy/utm' {
  declare module.exports: any;
}

declare module 'geodesy/vector3d' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geodesy/dms.js' {
  declare module.exports: $Exports<'geodesy/dms'>;
}
declare module 'geodesy/latlon-ellipsoidal.js' {
  declare module.exports: $Exports<'geodesy/latlon-ellipsoidal'>;
}
declare module 'geodesy/latlon-spherical.js' {
  declare module.exports: $Exports<'geodesy/latlon-spherical'>;
}
declare module 'geodesy/latlon-vectors.js' {
  declare module.exports: $Exports<'geodesy/latlon-vectors'>;
}
declare module 'geodesy/latlon-vincenty.js' {
  declare module.exports: $Exports<'geodesy/latlon-vincenty'>;
}
declare module 'geodesy/mgrs.js' {
  declare module.exports: $Exports<'geodesy/mgrs'>;
}
declare module 'geodesy/npm.js' {
  declare module.exports: $Exports<'geodesy/npm'>;
}
declare module 'geodesy/osgridref.js' {
  declare module.exports: $Exports<'geodesy/osgridref'>;
}
declare module 'geodesy/test/dms-tests.js' {
  declare module.exports: $Exports<'geodesy/test/dms-tests'>;
}
declare module 'geodesy/test/latlon-spherical-tests.js' {
  declare module.exports: $Exports<'geodesy/test/latlon-spherical-tests'>;
}
declare module 'geodesy/test/latlon-vectors-tests.js' {
  declare module.exports: $Exports<'geodesy/test/latlon-vectors-tests'>;
}
declare module 'geodesy/test/latlon-vincenty-tests.js' {
  declare module.exports: $Exports<'geodesy/test/latlon-vincenty-tests'>;
}
declare module 'geodesy/test/os-gridref-tests.js' {
  declare module.exports: $Exports<'geodesy/test/os-gridref-tests'>;
}
declare module 'geodesy/test/utm-mgrs-tests.js' {
  declare module.exports: $Exports<'geodesy/test/utm-mgrs-tests'>;
}
declare module 'geodesy/utm.js' {
  declare module.exports: $Exports<'geodesy/utm'>;
}
declare module 'geodesy/vector3d.js' {
  declare module.exports: $Exports<'geodesy/vector3d'>;
}
