// flow-typed signature: 1d24bbd0b3ec36adc432a213049fb6fe
// flow-typed version: <<STUB>>/leaflet-rotatedmarker_v^0.2.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-rotatedmarker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-rotatedmarker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-rotatedmarker/leaflet.rotatedMarker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-rotatedmarker/leaflet.rotatedMarker.js' {
  declare module.exports: $Exports<'leaflet-rotatedmarker/leaflet.rotatedMarker'>;
}
